name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build site with secrets
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          # Create build directory
          mkdir -p build
          
          # Copy static files
          cp index.html build/
          cp styles.css build/
          
          # Check if secrets are available
          if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
            echo "⚠️  Warning: Supabase secrets not configured. Site will use localStorage fallback."
            echo "To fix: Go to Settings > Secrets and variables > Actions and add:"
            echo "  - SUPABASE_URL (your Supabase project URL)"
            echo "  - SUPABASE_ANON_KEY (your Supabase anon public key)"
            cp script.js build/
          else
            echo "✅ Supabase secrets found, injecting into build..."
            # Use envsubst for more reliable replacement
            export SUPABASE_URL_PLACEHOLDER="YOUR_SUPABASE_URL_HERE"
            export SUPABASE_KEY_PLACEHOLDER="YOUR_SUPABASE_ANON_KEY_HERE"
            
            # Create script with replacements
            cat script.js | \
              sed "s|$SUPABASE_URL_PLACEHOLDER|$SUPABASE_URL|g" | \
              sed "s|$SUPABASE_KEY_PLACEHOLDER|$SUPABASE_ANON_KEY|g" \
              > build/script.js
            
            echo "✅ Build completed with Supabase credentials injected"
            echo "🔍 Verifying replacement..."
            grep -n "YOUR_SUPABASE_URL_HERE" build/script.js || echo "✅ URL placeholder replaced"
            grep -n "YOUR_SUPABASE_ANON_KEY_HERE" build/script.js || echo "✅ Key placeholder replaced"
          fi
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4